<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>Microchip IoT Ethernet Development Kit</title>
<link href="css/mchp-min.css" rel="stylesheet" type="text/css" />
<script src="javascript/mchp.js" type="text/javascript"></script>
</head>
<div id="page">
<div style="padding:0 0 5px 5px"><img src="images/mchp.gif" alt="Microchip" /></div>
<div id="title"><div class="left">Embedded Configuration Webpage</div><span id="hello">&nbsp;</span></div>